version: '3'
services:
  backend:
    build:
      context: "./Flask Server"
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - install-db
    container_name: backend
  frontend:
    build:
      context: ./React-site
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: frontend
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: db
    #volumes è un modo per salvare i dati di postgres fuori dal container, così se viene eliminato o altri danni, i dati permangono.
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d teamify -U postgres"]
      interval: 30s
      timeout: 15s
      retries: 5
  install-db:
    build:
      context: ./Install
      dockerfile: Dockerfile-install-db
    depends_on:
      - db
    container_name: install-db
volumes:
  db-data:
