version: '3'
services:
  backend:
    build:
      context: "./Flask Server"
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - install-db
    container_name: backend
    networks:
      - my-network
  frontend:
    build:
      context: ./React-site
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - my-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: db
    #volumes è un modo per salvare i dati di postgres fuori dal container, così se viene eliminato o altri danni, i dati permangono.
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my-network
  install-db:
    build:
      context: ./Install
      dockerfile: Dockerfile-install-db
    depends_on:
      - db
    container_name: install-db
    networks:
      - my-network
volumes:
  db-data:
networks:
  my-network: