version: '3'
services:
  backend:
    build:
      context: "./Flask Server"
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build:
      context: ./React-site
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #volumes è un modo per salvare i dati di postgres fuori dal container, così se viene eliminato o altri danni, i dati permangono.
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
