# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory to /app
WORKDIR /app

# Copy the installDB.py script into the container at /app
COPY installDB.py /app
COPY ../Flask\ Server/DBConnection.py /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run installDB.py when the container launches
CMD ["python", "installDB.py"]
